name: Test & release on push to main
on:   
  push:
    branches:
      - main
jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create build dir
        run: mkdir ./build
      - name: build
        run: make
      - name: run test
        run: ./bin/test_buffer
      - name: clean up 
      - run: rm -rf ./build
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          sudo apt-get install zip
          sudo apt-get install build-essential
      - name: create release dir
        run: mkdir ./release
      - name: package
        run: zip ./release/test_buffer.zip ./bin/test_buffer 
      - name: auto release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Version
          files: ./release/test_buffer.zip




